DROP TABLE IF EXISTS records CASCADE;
CREATE TABLE records (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  price FLOAT NOT NULL,
  genre VARCHAR(255) NOT NULL,
  artist_name VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  sold BOOLEAN DEFAULT FALSE,
  listing_views INTEGER,
  seller_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
