DROP TABLE IF EXISTS favourite_records CASCADE;
CREATE TABLE favourite_records (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  record_id INTEGER REFERENCES records(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);
